import 'package:flutter/cupertino.dart';

class Job {
  static GlobalKey<NavigatorState>mainListNav=GlobalKey();
  static GlobalKey<NavigatorState>mainAppNav=GlobalKey();
  static List<Job> getJob() => [
    Job(
        "Instagram Account Manager",
        "Kwakye Tripod",
        "Hall 7",
        "The description of the Job goes here",
        "25",
        "12th Dec 2021",
        "James Cameron",
        "James Cameron",
        "Zoe Saldana,Sigourney Weaver",
        "A paraplegic marine disoactched to the moon",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "assets/images/steven.jpg",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),
    Job(
        "Website Creation",
        "Chelsea Wiafe",
        "Src Hostel",
        "The description of the Job goes here",
        "160",
        "19th Dec 2021",
        "James Cameron",
        "James Cameron",
        "Zoe Saldana,Sigourney Weaver,Karikari Wiafe and Chelsy",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "assets/images/sam.jpg",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),
    Job(
        "Basic Electronics Tutor",
        "Eben Tyler",
        "Republic Hall",
        "The description of the Job goes here",
        "1,200",
        "20th Dec 2021",
        "James Cameron",
        "James Cameron",
        "Zoe Saldana,Sigourney Weaver,Karikari Wiafe and Chelsy",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "assets/images/greg.jpg",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),
    Job(
        "Graphic Design",
        "Bruce Kwakye",
        "Queens Hall",
        "The description of the Job goes here",
        "85",
        "10th Dec 2021",
        "James Cameron",
        "James Cameron",
        "Zoe Saldana,Sigourney Weaver,Karikari Wiafe and Chelsy",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "assets/images/james.jpg",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),

    Job(
        "Hair Dressing Service",
        "Tripod Chem",
        "Brunei Complex",
        "The description of the Job goes here",
        "80",
        "21st Dec 2021",
        "James Cameron",
        "James Cameron",
        "Zoe Saldana,Sigourney Weaver,Karikari Wiafe and Chelsy",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "assets/images/john.jpg",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),
    Job(
        "Windows Installation",
        "Lydia Kim",
        "Baby Brunei",
        "The description of the Job goes here",
        "650",
        "31st Dec 2021",
        "James Cameron",
        "James Cameron",
        "Zoe Saldana,Sigourney Weaver,Karikari Wiafe and Chelsy",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "assets/images/olivia.jpg",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),
    Job(
        "Basic Mechanics Tutor",
        "Anabel Carmelo",
        "Africa Hall",
        "The description of the Job goes here",
        "125",
        "12th Dec 2021",
        "James Cameron",
        "James Cameron",
        "Zoe Saldana,Sigourney Weaver,Karikari Wiafe and Chelsy",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "assets/images/sophia.jpg",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),


  ];
  String jobTitle='';
  String username = '';
  String location = '';
  String jobDescription = '';
  String price = '';
  String endDate = '';
  String director = '';
  String writer = '';
  String actors = '';
  String plot = '';
  String language = '';
  String other = '';
  String awards = '';
  String poster = '';
  String metaScore = '';
  String imdbRating = '';
  String imdbVotes = '';
  String imdbID = '';
  String type = '';
  String response = '';
  List<String> images = [];

  Job(
      this.jobTitle,
      this.username,
      this.location,
      this.jobDescription,
      this.price,
      this.endDate,
      this.director,
      this.writer,
      this.actors,
      this.plot,
      this.language,
      this.other,
      this.awards,
      this.poster,
      this.metaScore,
      this.imdbRating,
      this.imdbVotes,
      this.imdbID,
      this.type,
      this.response,
      this.images);
}
