import 'package:flutter/cupertino.dart';

class Job {
  static GlobalKey<NavigatorState>mainListNav=GlobalKey();
  static GlobalKey<NavigatorState>mainAppNav=GlobalKey();
  static List<Job> getJob() => [
    Job(
        "Job Description",
        "2002",
        "PG- 13",
        "The description of the Job goes here",
        "162 min",
        "Action",
        "James Cameron",
        "James Cameron",
        "Zoe Saldana,Sigourney Weaver",
        "A paraplegic marine disoactched to the moon",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "https://picsum.photos/300/300",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),
    Job(
        "Job Description",
        "2002",
        "PG- 13",
        "The description of the Job goes here",
        "162 min",
        "drummer,horror,sci-fi",
        "James Cameron",
        "James Cameron",
        "Zoe Saldana,Sigourney Weaver,Karikari Wiafe and Chelsy",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "https://picsum.photos/300/300",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),
    Job(
        "Job Description",
        "2002",
        "PG- 13",
        "The description of the Job goes here",
        "162 min",
        "drummer,horror,sci-fi",
        "James Cameron",
        "James Cameron",
        "Zoe Saldana,Sigourney Weaver,Karikari Wiafe and Chelsy",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "https://picsum.photos/300/300",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),
    Job(
        "Job Description",
        "2002",
        "PG- 13",
        "The description of the Job goes here",
        "162 min",
        "drummer,horror,sci-fi",
        "James Cameron",
        "James Cameron",
        "Zoe Saldana,Sigourney Weaver,Karikari Wiafe and Chelsy",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "https://picsum.photos/300/300",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),

    Job(
        "Job Description",
        "2002",
        "PG- 13",
        "The description of the Job goes here",
        "162 min",
        "drummer,horror,sci-fi",
        "James Cameron",
        "James Cameron",
        "Zoe Saldana,Sigourney Weaver,Karikari Wiafe and Chelsy",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "https://picsum.photos/300/300",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),
    Job(
        "Job Description",
        "2002",
        "PG- 13",
        "The description of the Job goes here",
        "162 min",
        "drummer,horror,sci-fi",
        "James Cameron",
        "James Cameron",
        "Zoe Saldana,Sigourney Weaver,Karikari Wiafe and Chelsy",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "https://picsum.photos/300/300",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),
    Job(
        "Job Description",
        "2002",
        "PG- 13",
        "The description of the Job goes here",
        "162 min",
        "drummer,horror,sci-fi",
        "James Cameron",
        "James Cameron",
        "Zoe Saldana,Sigourney Weaver,Karikari Wiafe and Chelsy",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "https://picsum.photos/300/300",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),


  ];
  String jobTitle='';
  String year = '';
  String rated = '';
  String jobDescription = '';
  String runtime = '';
  String genre = '';
  String director = '';
  String writer = '';
  String actors = '';
  String plot = '';
  String language = '';
  String country = '';
  String awards = '';
  String poster = '';
  String metaScore = '';
  String imdbRating = '';
  String imdbVotes = '';
  String imdbID = '';
  String type = '';
  String response = '';
  List<String> images = [];

  Job(
      this.jobTitle,
      this.year,
      this.rated,
      this.jobDescription,
      this.runtime,
      this.genre,
      this.director,
      this.writer,
      this.actors,
      this.plot,
      this.language,
      this.country,
      this.awards,
      this.poster,
      this.metaScore,
      this.imdbRating,
      this.imdbVotes,
      this.imdbID,
      this.type,
      this.response,
      this.images);
}
