import 'package:flutter/cupertino.dart';

class Job {
  static GlobalKey<NavigatorState>mainListNav=GlobalKey();
  static GlobalKey<NavigatorState>mainAppNav=GlobalKey();
  static List<Job> getJob() => [
    Job(
        "Social Media Marketer",
        "Kwakye Tripod",
        "Hall 7",
        "I need a highly skilled Social Media Marketer to manage the socal media account of my company",
        "25",
        "12th Dec 2021",
        "Instagram Account Manager",
        "Negotiable",
        "Social Networking",
        "A paraplegic marine disoactched to the moon",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "assets/images/steven.jpg",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),
    Job(
        "Website Designer",
        "Chelsea Wiafe",
        "Src Hostel",
        "I need an  excellent web developer. He has to be familiar with the modern frameworks to be able to complete this task",
        "160",
        "19th Dec 2021",
        "Website Creation",
        "Negotiable",
        "Designing",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "assets/images/sam.jpg",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),
    Job(
        "Academic Tutor",
        "Eben Tyler",
        "Republic Hall",
        "The description of the Job goes here",
        "1,200",
        "20th Dec 2021",
        "Chemistry Tutoring",
        "Non Negotiable",
        "Teaching",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "assets/images/greg.jpg",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),
    Job(
        "Graphic Designer",
        "Bruce Kwakye",
        "Queens Hall",
        "The description of the Job goes here",
        "85",
        "10th Dec 2021",
        "Graphic Design",
        "Non Negotiable",
        "Design",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "assets/images/james.jpg",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),

    Job(
        "Hair Dresser",
        "Tripod Chem",
        "Brunei Complex",
        "The description of the Job goes here",
        "80",
        "21st Dec 2021",
        "Hair Dressing Service",
        "Negotiable",
        "Hair Dressing",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "assets/images/john.jpg",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),
    Job(
        "Computer Specialist",
        "Lydia Kim",
        "Baby Brunei",
        "The description of the Job goes here",
        "650",
        "31st Dec 2021",
        "Windows Installation",
        "Negotiable",
        "Programming",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "assets/images/olivia.jpg",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),
    Job(
        "Academic Tutor",
        "Anabel Carmelo",
        "Africa Hall",
        "The description of the Job goes here",
        "125",
        "31st Dec 2021",
        "Basic Mechanics Tutoring",
        "Negotiable",
        "Teaching",
        "Years after a plague killed most of  humanity and transform the rest into mosters,the sole survivor in NewYork City Struggles to find a cure",
        "English, Spanish",
        "USA,UK",
        "Won 3 Oscars. Another 80 wins & 121 nominations",
        "assets/images/sophia.jpg",
        "83",
        "7.9",
        "890,617",
        "tt0499545",
        "movie",
        "True",
        ["https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300",
          "https://picsum.photos/300/300"]),


  ];
  String requestTitle='';
  String username = '';
  String location = '';
  String jobDescription = '';
  String price = '';
  String endDate = '';
  String jobTitle = '';
  String negotiability = "";
  String requiredSkills = '';
  String plot = '';
  String language = '';
  String other = '';
  String awards = '';
  String poster = '';
  String metaScore = '';
  String imdbRating = '';
  String imdbVotes = '';
  String imdbID = '';
  String type = '';
  String response = '';
  List<String> images = [];

  Job(
      this.jobTitle,
      this.username,
      this.location,
      this.jobDescription,
      this.price,
      this.endDate,
      this.requestTitle,
      this.negotiability,
      this.requiredSkills,
      this.plot,
      this.language,
      this.other,
      this.awards,
      this.poster,
      this.metaScore,
      this.imdbRating,
      this.imdbVotes,
      this.imdbID,
      this.type,
      this.response,
      this.images);
}
